### ISSUE TITLE
Add to Grape projects

### ISSUE THREAD

**Issue by dblock** [codescrum/grape-transformations#2]
Add to https://github.com/ruby-grape/ruby-grape.github.io/blob/master/projects/index.md, please.

**Comment by johaned** [comment]
Hey @dblock thanks for checking out our gem. we really appreciate it! Sure! we will submit a pull request soon to add it in the listing. [Please note that this gem works with some grape versions ('>= 0.7.0', '<= 0.9.0'), we are thinking to upgrade it in the near future]

**Comment by dblock** [comment]
:+1:

**Comment by johaned** [comment]
hi @dblock!!, we were looking into the projects index page to add our gem, however, we are not pretty sure where to put it. It has some routing (because of the "smart endpoints"), it also has some generators, it also deals with entities in some sense, it seems like it could fit in the "opinionated frameworks" section, but it is not entirely a "framework" per se, since does not force you to use it as a base if you don't want to. 

Could you recommend us a place in which it could fit best?

Thanks!

**Comment by dblock** [comment]
I think it's best to put it into the opinionated frameworks, that was my "catch-all" :)

**Comment by johaned** [comment]
Ok it's done :+1:
